mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_app.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/news_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.NewsHomeView.as_view(), name='index'),
    path('category/<slug:categories_name>/', views.NewsCategoryView.as_view(), name='categories'),
    path('post/<slug:post_name>/', views.ShowPostView.as_view(), name='post'),
    path('search/', views.NewsSearchView.as_view(), name='news-search'),
    path('create/', views.NewsCreateView.as_view(), name='create-post'),
    path('<slug:post_name>/update/', views.NewsUpdateView.as_view(), name='update-post'),
    path('<slug:post_name>/delete/', views.NewsDeleteView.as_view(), name='delete-post'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('logout/', views.logout_user, name='logout'),
]

mysite/news_app/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core import validators


class Category(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('categories', kwargs={'categories_name': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class News(models.Model):
    title = models.CharField(max_length=120, verbose_name='Заголовок', validators=[validators.MinLengthValidator(12)])
    content = models.TextField(verbose_name='Контент', validators=[validators.MinLengthValidator(25)])
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, verbose_name='Фото')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_name': self.slug})

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-created_at']


class Comment(models.Model):
    news = models.ForeignKey('News', on_delete=models.CASCADE, verbose_name='Новость')
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Имя пользователя')
    content = models.TextField(max_length=255, verbose_name='Текст комментария')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created_at']

mysite/news_app/forms.py
from django import forms
from .models import News, Comment
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms.widgets import HiddenInput


class NewsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Категория не выбрана'
        self.fields['is_published'].label = 'Опубликовать'

    class Meta:
        model = News
        fields = ['title', 'slug', 'content', 'category', 'is_published']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'ФРС США повысила ставку до 4%', 'rows': 6}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Login'}))
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='Повтор паооля', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Login'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].label = 'Написать комментарий'
        self.fields['news'].widget = HiddenInput()
        self.fields['username'].widget = HiddenInput()

    class Meta:
        model = Comment
        fields = ['username', 'content', 'news']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'cols': 120, 'placeholder': 'Напишите комментарий'}),
        }

mysite/news_app/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import ModelFormMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, logout

from .models import Category, News, Comment
from .forms import CommentForm, NewsForm, RegisterUserForm, LoginUserForm
from .utils import DataMixin


class NewsHomeView(DataMixin, ListView):
    model = News
    template_name = 'news_app/index.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return context | c_def

    def get_queryset(self):
        return News.objects.filter(is_published=True).select_related('category')


class NewsCategoryView(DataMixin, ListView):
    model = News
    template_name = 'news_app/show_category.html'
    context_object_name = 'news'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(slug=self.kwargs['categories_name'])
        c_def = self.get_user_context(cat_selected=self.kwargs['categories_name'])
        return context | c_def

    def get_queryset(self):
        return News.objects.filter(category__slug=self.kwargs['categories_name'], is_published=True).select_related('category')


class ShowPostView(ModelFormMixin, DetailView):
    model = News
    form_class = CommentForm
    template_name = 'news_app/show_post.html'
    context_object_name = 'post'
    slug_url_kwarg = 'post_name'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(news__slug=self.kwargs['post_name']).select_related('username')
        context['form'] = CommentForm(initial={'username': self.request.user, 'news': self.object})
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = self.get_object()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('post', kwargs={'post_name': self.kwargs['post_name']})


class NewsSearchView(DataMixin, ListView):
    model = News
    template_name = 'news_app/index.html'
    context_object_name = 'news'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return context | c_def

    def get_queryset(self):
        query = self.request.GET.get('q')
        return News.objects.filter(title__icontains=query, is_published=True).select_related('category')


class NewsUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'news_app.change_post'
    model = News
    template_name = 'news_app/create_post.html'
    slug_url_kwarg = 'post_name'
    form_class = NewsForm


class NewsDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'news_app.delete_post'
    model = News
    slug_url_kwarg = 'post_name'
    success_url = reverse_lazy('index')


class NewsCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'news_app.add_news'
    form_class = NewsForm
    template_name = 'news_app/create_post.html'
    success_url = reverse_lazy('index')


class RegisterUserView(CreateView):
    form_class = RegisterUserForm
    template_name = 'news_app/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')


class LoginUserView(LoginView):
    form_class = LoginUserForm
    template_name = 'news_app/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('index')


def logout_user(request):
    logout(request)
    return redirect('index')

mysite/news_app/templates/news_app/base.html
{% load static %}
{% load news_app_tags %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>{% block title %}{% endblock%}</title>
</head>

<body>

    {% include 'news_app/inc/nav.html' %}

    <div class="container mt-3">
        <div class="row">

            {% show_categories cat_selected %}
            <div class="col-9">
                {% block content %}{% endblock content%}
                {% include 'news_app/inc/pagination.html' %}
            </div>

        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

mysite/news_app/templates/news_app/create_post.html
{% extends 'news_app/base.html' %}

{% block title %}
    ПрессРу: Добавить статью
{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <div class="form-group">
                {% if f.label != 'Опубликовать' %}
                    <label for={{ f.id_for_label }}>{{ f.label }}</label>
                    {{ f }}
                    <div class="form-error">{{ f.errors }}</div>
                {% else %}
                    {{ f }}
                    <label class="form-check-label" for={{ f.id_for_label }}>{{ f.label }}</label>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Создать статью</button>
    </form>
{% endblock content %}

mysite/news_app/templates/news_app/index.html
{% extends 'news_app/base.html' %}

{% block title %}
    ПрессРу: Новости
{% endblock title %}

{% block content %}
    {% if news|length != 0 %}
        {% for post in news %}
            <div class="card">
                <h5 class="card-header">Категория: {{ post.category }}</h5>
                <div class="card-body">
                    <h5 class="card-title"> {{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatechars:300 }}</p>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать далее</a>
                </div>
                <div class="card-footer text-muted">
                    {{ post.created_at|date:"Y-m-d H:i:s" }}
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h1>Нет новостей по вашему запросу</h1>
    {% endif %}
{% endblock content %}

mysite/news_app/templates/news_app/list_categories.html
<div class="col-3">
    <div class="list-group">
        {% if cat_selected == 0 %}
            <a href="{% url 'index' %}" class="list-group-item list-group-item-action active">Все категории</a>
        {% else %}
            <a href="{% url 'index' %}" class="list-group-item list-group-item-action">Все категории</a>
        {% endif %}
        {% for category in cats %}
            {% if category.slug == cat_selected %}
                <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action active">{{ category.name }}</a>
            {% else %}
                <a href="{{ category.get_absolute_url }}" class="list-group-item list-group-item-action">{{ category.name }}</a>
            {% endif %}
        {% endfor %}
    </div>
</div>

mysite/news_app/templates/news_app/login.html
{% extends 'news_app/base.html' %}

{% block title %}
    ПрессРу: Авторизация
{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_erros }}</div>
        {% for f in form %}
            <div class="form-group">
                <label for={{ f.id_for_label }}>{{ f.label }}</label>
                {{ f }}
                <div class="form-error">{{ f.errors }}</div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Войти</button>
{% endblock content %}

mysite/news_app/templates/news_app/register.html
{% extends 'news_app/base.html' %}

{% block title %}
    ПрессРу: Регистрация
{% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <div class="form-group">
                <label for={{ f.id_for_label }}>{{ f.label }}</label>
                {{ f }}
                <div class="form-error">{{ f.errors }}</div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
{% endblock content %}

mysite/news_app/templates/news_app/show_category.html
{% extends 'news_app/base.html' %}

{% block title %}
    {{ category.name }} - Новости ПрессРу
{% endblock title %}

{% block content %}
    {% if news|length != 0 %}
        {% for post in news %}
            <div class="card">
                <h5 class="card-header">Категория: {{ post.category }}</h5>
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatechars:300 }}</p>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать далее</a>
                </div>
                <div class="card-footer text-muted">
                    {{ post.created_at|date:"Y-m-d H:i:s" }}
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h1>Нет постов в этой категории</h1>
    {% endif %}
    {% include 'news_app/inc/pagination.html' %}
{% endblock content %}

mysite/news_app/templates/news_app/show_post.html
{% extends 'news_app/base.html' %}

{% block title %}
    {{ post.category.name }} - Новости ПрессРу
{% endblock title %}

{% block content %}
    {% if perms.news_app.change_news and perms.news_app.delete_news %}
        <div>
            <form method="POST" action="{% url 'delete-post' post.slug %}" style="margin: 0">
                {% csrf_token %}
                <a href="{% url 'update-post' post.slug %}" class="btn btn-secondary">Редактировать</a>
                <input class="btn btn-danger" type="submit" value="Удалить">
            </form>
        </div>
        <br>
    {% endif %}
    
    <div class="card">
        <h5 class="card-header">Категория: {{ post.category }}</h5>
        <div class="card-body">
            <h5 class="card-title"> {{ post.title }}</h5>
            <p class="card-text">{{ post.content }}</p>
        </div>
        <div class="card-footer text-muted">
            {{ post.created_at|date:"Y-m-d H:i:s" }}
        </div>
    </div>
    <br>

    {% include 'news_app/inc/comment_form.html' %}

    {% for comment in comments %}
        <br>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ comment.username }}</h5>
                <p class="card-text">{{ comment.content }}</p>
                <hr>
                <p class="card-text">{{ comment.created_at }}</p>
            </div>
        </div>
    {% endfor %}
    <br>
{% endblock content %}